name: Whatsapp Bot Links

on:
  push:
    branches: [master]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm install
          # Garante as permissões das bibliotecas do Chrome no Linux
          npx puppeteer browsers install chrome

      - name: Start Bot
        run: npm start
